import mysql.connector
db_connect=mysql.connector.connect(host="localhost",user="root",password="asap",database='school')
db_cursor=db_connect.cursor()
db_cursor.execute("create table student(Id int primary key,Name varchar(30),Age int)")
db_connect.commit()
db_cursor.execute("create table employees(id int, First_name varchar(20),Place varchar(20))")
db_cursor.execute("insert into student(Id,Name,Age)values(1,'Arun',12)")
db_connect.commit()
db_cursor.execute("insert into student(Id,Name,Age)values(2,'Vivek',11)")
db_connect.commit()
db_cursor.execute("insert into student(Id,Name,Age)values(3,'Akhil',13)")
db_connect.commit()
db_cursor.execute('update student set Id="Roll no.", Name="first name" where Id=1')
db_connect.commit()
db_cursor.execute("alter table employees drop Place")
db_connect.commit()
db_cursor.execute("delete from student where Id=2")
db_connect.commit()
db_connect.close()
